- name: configure mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - PyMySQL

  - name: install mysql-server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start mysql-server service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: Connect to MySQL server
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: 172.31.27.59
    register: mysql_connection_output
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "Mysql info: {{ mysql_connection_output }}"


    
